// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZzi6q2kttew7pgHfDUmVqNAvsGlTkLhQ',
    appId: '1:103420377750:web:59d01754a87920694de0b7',
    messagingSenderId: '103420377750',
    projectId: 'ecommerceapp-5f2f0',
    authDomain: 'ecommerceapp-5f2f0.firebaseapp.com',
    storageBucket: 'ecommerceapp-5f2f0.appspot.com',
    measurementId: 'G-KKY8N4K2W4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnOjAUf2lUnYtjkw-250TfXNUkNXs1c9U',
    appId: '1:103420377750:android:144adf1eceb60ed34de0b7',
    messagingSenderId: '103420377750',
    projectId: 'ecommerceapp-5f2f0',
    storageBucket: 'ecommerceapp-5f2f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNKg9yI1TWBVusz08sXyYIOzGJEOt___U',
    appId: '1:103420377750:ios:044f45c140f4a7024de0b7',
    messagingSenderId: '103420377750',
    projectId: 'ecommerceapp-5f2f0',
    storageBucket: 'ecommerceapp-5f2f0.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNKg9yI1TWBVusz08sXyYIOzGJEOt___U',
    appId: '1:103420377750:ios:0eee141c6022de394de0b7',
    messagingSenderId: '103420377750',
    projectId: 'ecommerceapp-5f2f0',
    storageBucket: 'ecommerceapp-5f2f0.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
